#python denoise_dir.py --model_subdir 2018-12-16T03:11_run_nn.py_--test_reserve_threebicycles_droid_MuseeL-Vanillekipferl_MuseeL-Ndengese_ursulines-red_stefantiek_--batch_size_94
#python denoise_dir.py --model_subdir 2018-12-16T03:29_run_nn.py_--test_reserve_threebicycles_droid_MuseeL-Vanillekipferl_MuseeL-Ndengese_ursulines-red_stefantiek_--batch_size_94_--sigmamin_1_--sigmamax_60_--yisx_--cuda_device_1
#python loss.py --noisy_dir results/test/GT
python loss.py --noisy_dir results/test/bm3d-10
python loss.py --noisy_dir results/test/bm3d-20
python loss.py --noisy_dir results/test/bm3d-30
python loss.py --noisy_dir results/test/bm3d-40
python loss.py --noisy_dir results/test/bm3d-50
python loss.py --noisy_dir results/test/bm3d-60
python loss.py --noisy_dir results/test/bm3d-70
python loss.py --noisy_dir results/test/bm3d-80
python loss.py --noisy_dir results/test/bm3d-90
