python3 -u p2p_train.py --min_ssim_l 0.3 --post_fail_ssim_num 150 --weight_ssim 0.4 --weight_L1 0.1 --keep_D --test_reserve ursulines-red stefantiek ursulines-building MuseeL-Bobo CourtineDeVillersDebris C500D --cuda_device 1 --batch_size 45 &> 'results/train/--min_ssim_l,0.3,--post_fail_ssim_num,150,--weight_ssim,0.4,--weight_L1,0.1'
python3 -u p2p_train.py --min_ssim_l 0.15 --post_fail_ssim_num 70 --weight_ssim 0.4 --weight_L1 0.1 --keep_D --test_reserve ursulines-red stefantiek ursulines-building MuseeL-Bobo CourtineDeVillersDebris C500D --cuda_device 1 --batch_size 45 &> 'results/train/--min_ssim_l,0.15,--post_fail_ssim_num,70,--weight_ssim,0.4,--weight_L1,0.1'
python3 -u p2p_train.py --min_ssim_l 0.125 --post_fail_ssim_num 35 --weight_ssim 0.4 --weight_L1 0.1 --keep_D --test_reserve ursulines-red stefantiek ursulines-building MuseeL-Bobo CourtineDeVillersDebris C500D --cuda_device 1 --batch_size 45 &> 'results/train/--min_ssim_l,0.125,--post_fail_ssim_num,35,--weight_ssim,0.4,--weight_L1,0.1'
python3 -u p2p_train.py --min_ssim_l 0.15 --post_fail_ssim_num 70 --weight_ssim 0.9 --weight_L1 0.05 --keep_D --test_reserve ursulines-red stefantiek ursulines-building MuseeL-Bobo CourtineDeVillersDebris C500D --cuda_device 1 --batch_size 45 &> 'results/train/--min_ssim_l,0.15,--post_fail_ssim_num,70,--weight_ssim,0.9,--weight_L1,0.05'
python3 -u p2p_train.py --min_ssim_l 0.125 --post_fail_ssim_num 35 --weight_ssim 0.9 --weight_L1 0.05 --keep_D --test_reserve ursulines-red stefantiek ursulines-building MuseeL-Bobo CourtineDeVillersDebris C500D --cuda_device 1 --batch_size 45 &> 'results/train/--min_ssim_l,0.125,--post_fail_ssim_num,35,--weight_ssim,0.9,--weight_L1,0.05'
python3 -u p2p_train.py --min_ssim_l 0.3 --post_fail_ssim_num 150 --weight_ssim 0.9 --weight_L1 0.05 --keep_D --test_reserve ursulines-red stefantiek ursulines-building MuseeL-Bobo CourtineDeVillersDebris C500D --cuda_device 1 --batch_size 45 &> 'results/train/--min_ssim_l,0.3,--post_fail_ssim_num,150,--weight_ssim,0.9,--weight_L1,0.05'
python3 -u p2p_train.py --min_ssim_l 0.15 --post_fail_ssim_num 70 --weight_ssim 0.075 --weight_L1 0.025 --keep_D --test_reserve ursulines-red stefantiek ursulines-building MuseeL-Bobo CourtineDeVillersDebris C500D --cuda_device 1 --batch_size 45 &> 'results/train/--min_ssim_l,0.15,--post_fail_ssim_num,70,--weight_ssim,0.075,--weight_L1,0.025'
python3 -u p2p_train.py --min_ssim_l 0.125 --post_fail_ssim_num 35 --weight_ssim 0.075 --weight_L1 0.025 --keep_D --test_reserve ursulines-red stefantiek ursulines-building MuseeL-Bobo CourtineDeVillersDebris C500D --cuda_device 1 --batch_size 45 &> 'results/train/--min_ssim_l,0.125,--post_fail_ssim_num,35,--weight_ssim,0.075,--weight_L1,0.025'
python3 -u p2p_train.py --min_ssim_l 0.3 --post_fail_ssim_num 150 --weight_ssim 0.075 --weight_L1 0.025 --keep_D --test_reserve ursulines-red stefantiek ursulines-building MuseeL-Bobo CourtineDeVillersDebris C500D --cuda_device 1 --batch_size 45 &> 'results/train/--min_ssim_l,0.3,--post_fail_ssim_num,150,--weight_ssim,0.075,--weight_L1,0.025'
python3 -u p2p_train.py --min_ssim_l 0.15 --post_fail_ssim_num 70 --weight_ssim 0.4 --weight_L1 0.1 --keep_D --D_ratio 0.8 --test_reserve ursulines-red stefantiek ursulines-building MuseeL-Bobo CourtineDeVillersDebris C500D --cuda_device 1 --batch_size 45 &> 'results/train/--min_ssim_l,0.15,--post_fail_ssim_num,70,--weight_ssim,0.4,--weight_L1,0.1,--D_ratio,0.8'
python3 -u p2p_train.py --min_ssim_l 0.15 --post_fail_ssim_num 70 --weight_ssim 0.4 --weight_L1 0.1 --keep_D --D_ratio 0.2 --test_reserve ursulines-red stefantiek ursulines-building MuseeL-Bobo CourtineDeVillersDebris C500D --cuda_device 1 --batch_size 45 &> 'results/train/--min_ssim_l,0.15,--post_fail_ssim_num,70,--weight_ssim,0.4,--weight_L1,0.1,--D_ratio,0.2'


